name: Docker Deploy to Remote Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      #      - name: Login to DockerHub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #      - name: Build and Push Docker image
      #        run: |
      #          docker build -t cj180525/art-pro:latest .
      #          docker push cj180525/art-pro:latest

      - name: Build and Push Docker image
        run: docker build -t art-pro:latest .

      - name: Save Docker image to tar
        run: docker save art-pro:latest -o art-pro.tar

      - name: Copy tar to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: aas
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "art-pro.tar"
          target: "~/art-pro/"


      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: aas
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/art-pro/art-pro.tar
            docker stop art-pro || true
            docker rm art-pro || true
            docker-compose -f /home/aas/art-pro/docker-compose.yml up -d
