name: Docker Deploy to Remote Server

on:
  push:
    branches: [ "main" ]

jobs:
   deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: cj180525@gmail.com
          password: wc@123456

      - name: Build and Push Docker image
        run: |
          docker build -t cj180525/art-pro:latest .
          docker push cj180525/art-pro:latest .

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 123.60.104.131
          username: aas
          key: nbcb,111
          script: |
            docker pull cj180525/art-pro:latest
            docker stop cj180525/art-pro || true
            docker rm cj180525/art-pro || true
            docker-compose -f /path/to/docker-compose.yml up -d
